services:
  db:
    image: mysql:8.0
    container_name: messaging_app_db
    restart: always

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB: ${DB_HOST}

    ports:
      - "3306:3306"

    volumes:
      - messaging_app_db:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: .
    container_name: messaging_app
    # command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

volumes:
  messaging_app_db:
