services:
  db:
    image: postgres
    container_name: messaging_app_db
    volumes:
      - messaging_app_db:/var/lib/postgresql/data
    
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


  web:
    build: .
    container_name: messaging_app
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      
    depends_on:
      db:
        condition: service_healthy
    restart: always

    env_file:
      - .env
      
   
volumes:
  messaging_app_db: