apiVersion: v1
kind: Secret
metadata:
  name: messaging-mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==         # "root"
  mysql-user: bWVzc2FnaW5n              # "messaging"
  mysql-password: b3B0aW9uYWw=          # "optional"
  mysql-database: bWVzc2FnaW5nX2Ri      # "messaging_db"
