# Generated by Django 5.2.6 on 2025-09-22 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="participants_id",
        ),
        migrations.AddField(
            model_name="conversation",
            name="participants_id",
            field=models.ManyToManyField(
                related_name="conversation", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
